services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: framer_university
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data:delegated

    backend:
        build:
            context: .
            dockerfile: backend.Dockerfile
        ports:
            - "8080:8080"
        environment:
            - DATABASE_URL=postgres://postgres:password@postgres:5432/framer_university
        depends_on:
            - postgres
        volumes:
            - ./src:/app/src:delegated
            - target-cache:/app/target:delegated

    frontend:
        build:
            context: .
            dockerfile: frontend.Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./app:/app/app:delegated
        depends_on:
            - backend

volumes:
    postgres-data:
    target-cache:
