app = 'learn-framer-university-staging'
primary_region = 'lhr'

[build]
dockerfile = 'frontend.staging.Dockerfile'

[build.args]
BACKEND_URL = 'http://learn-framer-university-api-staging.fly.dev'
NODE_ENV = 'staging'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
