app = 'learn-framer-university-api'
primary_region = 'lhr'

[build]
dockerfile = 'frontend.Dockerfile'

[env]
ALLOWED_ORIGINS = ['https://learn.framer.university']
INSTANCE_METRICS_LOG_EVERY_SECONDS = 60
JWT_ACCESS_TOKEN_EXPIRATION_HOURS = 24
JWT_REFRESH_TOKEN_EXPIRATION_DAYS = 7
EMAIL_VERIFICATION_EXPIRATION_HOURS = 48
CONNECTION_TIMEOUT_SECONDS = 3
POOL_SIZE = 3
APP_URL= 'https://api.learn.framer.university'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
