app = 'learn-framer-university-api-staging'
primary_region = 'lhr'

[build]
dockerfile = 'api.staging.Dockerfile'

[env]
ALLOWED_ORIGINS = ['http://learn-framer-university-staging.fly.dev']
INSTANCE_METRICS_LOG_EVERY_SECONDS = 30
JWT_ACCESS_TOKEN_EXPIRATION_HOURS = 24
JWT_REFRESH_TOKEN_EXPIRATION_DAYS = 7
EMAIL_VERIFICATION_EXPIRATION_HOURS = 48
CONNECTION_TIMEOUT_SECONDS = 2
POOL_SIZE = 2

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/v1"
