app = 'learn-framer-university-api'
primary_region = 'lhr'

[build]
dockerfile = 'api.Dockerfile'

[build.args]
BUILD_PROFILE = 'release'
INSTALL_EXTRA_CERTS = 'false'
RUST_LOG_LEVEL = 'warn'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1