app = 'learn-framer-university'
primary_region = 'lhr'

[build]
dockerfile = 'frontend.Dockerfile'

[build.args]
NEXT_PUBLIC_API_URL = 'https://api.learn.framer.university'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
