app = 'learn-framer-university-staging'
primary_region = 'lhr'

[build]
dockerfile = 'frontend.staging.Dockerfile'

[build.args]
API_URL = 'http://learn-framer-university-api-staging.fly.dev'

[env]
APP_URL= 'http://learn-framer-university-staging.fly.dev'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
