on:
    push:
        branches: ["main"]

env:
    # renovate: datasource=npm depName=pnpm
    PNPM_VERSION: 10.11.0
    # Turborepo
    TURBO_API: ${{ vars.TURBO_API }}
    TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_REMOTE_CACHE_SIGNATURE_KEY: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
    # Neon
    DATABASE_URL: ${{ vars.DATABASE_URL }}
    # Fly
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    # Cloudflare
    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    # Chromatic
    CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3
              with:
                  version: ${{ env.PNPM_VERSION }}

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: 1.85.0
                  components: clippy, rustfmt

            - run: cargo install sqlx-cli@0.8.5 --locked --no-default-features --features native-tls,postgres
            - run: cargo sqlx database create && sqlx migrate run
            - run: cargo sqlx prepare --check -- --all-targets

            - run: pnpm install
            - run: cd apps/web && pnpm playwright install chromium
            - run: pnpm run ci

    deploy:
        needs: ci
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3
              with:
                  version: ${{ env.PNPM_VERSION }}

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - run: pnpm install
            - run: pnpm build

            - name: Deploy web to Cloudflare
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  workingDirectory: "apps/web"

            - name: Deploy admin to Cloudflare
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  workingDirectory: "apps/admin"

            - name: Deploy plugin to Cloudflare
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  workingDirectory: "apps/plugin"

            - name: Deploy Storybook to Chromatic
              uses: chromaui/action@latest
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  workingDir: apps/storybook
                  exitOnceUploaded: true

            - uses: superfly/flyctl-actions/setup-flyctl@master
            - name: Deploy API to Fly
              run: |
                  cd apps/api
                  flyctl deploy
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
